-- schema.sql
-- Database structures for the Ebilling System (Oracle SQL 11g XE)

-- Drop tables if they exist
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE bill_items CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL; END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE bills CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL; END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE products CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL; END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE categories CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL; END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE users CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL; END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE shops CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL; END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE notes CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL; END;
/

-- Drop sequences if they exist
BEGIN
  EXECUTE IMMEDIATE 'DROP SEQUENCE seq_category_id';
EXCEPTION WHEN OTHERS THEN NULL; END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP SEQUENCE seq_product_id';
EXCEPTION WHEN OTHERS THEN NULL; END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP SEQUENCE seq_bill_id';
EXCEPTION WHEN OTHERS THEN NULL; END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP SEQUENCE seq_bill_item_id';
EXCEPTION WHEN OTHERS THEN NULL; END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP SEQUENCE seq_note_id';
EXCEPTION WHEN OTHERS THEN NULL; END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP SEQUENCE seq_shop_num';
EXCEPTION WHEN OTHERS THEN NULL; END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP SEQUENCE seq_user_num';
EXCEPTION WHEN OTHERS THEN NULL; END;
/

-- Create sequences
CREATE SEQUENCE seq_category_id START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE seq_product_id START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE seq_bill_id START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE seq_bill_item_id START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE seq_note_id START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE seq_shop_num START WITH 1001 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE seq_user_num START WITH 1001 INCREMENT BY 1 NOCACHE;

-- Create SHOPS table
CREATE TABLE shops (
  shop_id VARCHAR2(30) PRIMARY KEY,
  shop_name VARCHAR2(100) NOT NULL,
  place VARCHAR2(100) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- Create USERS table
CREATE TABLE users (
  user_id VARCHAR2(30) PRIMARY KEY,
  name VARCHAR2(100) NOT NULL,
  password VARCHAR2(100) NOT NULL,
  role VARCHAR2(20) NOT NULL,
  shop_id VARCHAR2(30) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  CONSTRAINT chk_user_role CHECK (role IN ('shopkeeper', 'worker')),
  CONSTRAINT fk_users_shop FOREIGN KEY (shop_id) REFERENCES shops(shop_id) ON DELETE CASCADE
);

-- Create CATEGORIES table
CREATE TABLE categories (
  category_id NUMBER PRIMARY KEY,
  shop_id VARCHAR2(30) NOT NULL,
  name VARCHAR2(50) NOT NULL,
  CONSTRAINT fk_categories_shop FOREIGN KEY (shop_id) REFERENCES shops(shop_id) ON DELETE CASCADE,
  CONSTRAINT uq_shop_category UNIQUE (shop_id, name)
);

-- Create PRODUCTS table
CREATE TABLE products (
  product_id NUMBER PRIMARY KEY,
  shop_id VARCHAR2(30) NOT NULL,
  name VARCHAR2(100) NOT NULL,
  category_id NUMBER NOT NULL,
  price NUMBER(10, 2) NOT NULL,
  stock NUMBER(10, 2) NULL,
  quantity_unit VARCHAR2(30) NOT NULL,
  image_url VARCHAR2(500) NULL,
  CONSTRAINT fk_products_shop FOREIGN KEY (shop_id) REFERENCES shops(shop_id) ON DELETE CASCADE,
  CONSTRAINT fk_products_category FOREIGN KEY (category_id) REFERENCES categories(category_id) ON DELETE CASCADE
);

-- Create BILLS table
CREATE TABLE bills (
  bill_id NUMBER PRIMARY KEY,
  shop_id VARCHAR2(30) NOT NULL,
  bill_number VARCHAR2(50) NOT NULL,
  customer_name VARCHAR2(100),
  customer_phone VARCHAR2(20),
  bill_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  total_amount NUMBER(12, 2) NOT NULL,
  discount NUMBER(12, 2) DEFAULT 0 NOT NULL,
  tax NUMBER(12, 2) DEFAULT 0 NOT NULL,
  grand_total NUMBER(12, 2) NOT NULL,
  created_by VARCHAR2(30) NOT NULL,
  CONSTRAINT fk_bills_shop FOREIGN KEY (shop_id) REFERENCES shops(shop_id) ON DELETE CASCADE,
  CONSTRAINT fk_bills_creator FOREIGN KEY (created_by) REFERENCES users(user_id),
  CONSTRAINT uq_shop_bill UNIQUE (shop_id, bill_number)
);

-- Create BILL_ITEMS table
CREATE TABLE bill_items (
  bill_item_id NUMBER PRIMARY KEY,
  bill_id NUMBER NOT NULL,
  product_id NUMBER,
  product_name VARCHAR2(100) NOT NULL,
  quantity NUMBER(10, 2) NOT NULL,
  price NUMBER(10, 2) NOT NULL,
  subtotal NUMBER(12, 2) NOT NULL,
  CONSTRAINT fk_items_bill FOREIGN KEY (bill_id) REFERENCES bills(bill_id) ON DELETE CASCADE
);

-- Create NOTES table
CREATE TABLE notes (
  note_id NUMBER PRIMARY KEY,
  shop_id VARCHAR2(30) NOT NULL,
  item_name VARCHAR2(100) NOT NULL,
  quantity VARCHAR2(50),
  notes VARCHAR2(200),
  status VARCHAR2(20) DEFAULT 'pending' NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  CONSTRAINT chk_notes_status CHECK (status IN ('pending', 'ordered', 'received')),
  CONSTRAINT fk_notes_shop FOREIGN KEY (shop_id) REFERENCES shops(shop_id) ON DELETE CASCADE
);

EXIT;
